### ISSUE TITLE
Release TOPT tolerance code with version bump on crates.io

### ISSUE THREAD

**Issue by YetAnotherMinion** [breard-r/libreauth#1]
I noticed that some new features have been merged into master that are not available on the `v0.5.2` available from crates.io.

**Comment by breard-r** [comment]
You are right, I worked a bit on HOTP/TOTP since version 0.5.2. There is two reasons that explains why I have not released anything since. The first one is because of my work on the password authentication that is still highly experimental, will have breaking changes and is still considered as unsecured and therefore should not be used yet. If I release it, people will start to use it anyway and that may be dangerous for them. The second reason is because I didn't thought people were already using this lib. I did very little communication about it and planned to talk about it one I got a decent password authentication.
I guess that was not a wish choice not to release anything since, I will work on it in the next days. Thank you for your feedback :)

**Comment by YetAnotherMinion** [comment]
There is a [blog series](https://skinkade.github.io/rocket-jwt-roles-demo/) about using two factor authentication with rust web frameworks that uses your crate because it has the nicest interface of the 5 that deal with this area.
