### ISSUE TITLE
Password authentication status

### ISSUE THREAD

**Issue by alexwl** [breard-r/libreauth#11]
Hi!

The README says that password authentication is not ready yet.

I've read the code and it seems to me that all the necessary features are implemented and the API is pretty clear.

Is there anything that should be done before password authentication can be considered ready/complete ?

**Comment by breard-r** [comment]
Hello!

As marked on the readme, the password authentication is not ready yet. I flagged it as "unstable API" because I had to rewrite it several times before having the current implementation. Currently, I think the current one is ok and should be stabilized, but I need to confirm it by adding a few features. This brings us to the next topic, the "incomplete" flag. Indeed, this implementation is much more complete than many others. However, doing better than most is not enough and there is still a few things to add. The most important improvement is already developed and almost ready to be pushed. It is an additional hash round (HMAC-SHA2) using an external salt which is executed either before or after the real hash computation. This is a recommendation from the NIST that helps defeating most (but not all) database leaks (because the salt isn't in the database, there is a high probability it hasn't leaked).

A second point of attention is about the C-bindings. Those are incomplete and badly written, hence I cannot really say this API is fully stabilized while the C one may change at any moment. I already planned to rewrite those bindings.

That said, I think it's quite safe to assume it is currently usable in a Rust environment. Now there is a password version, the future functionalities should be correctly handled. But keep an eye on the change log while upgrading.

**Comment by alexwl** [comment]
Thanks for the detailed response!

> The most important improvement is already developed and almost ready to be pushed. It is an additional hash round (HMAC-SHA2) using an external salt which is executed either before or after the real hash computation.

This is a great feature to have, especially when it is possible to deploy a physically separate server dedicated to password validation. The downside of using an external salt (stored outside of the database), I guess, is that it complicates the backup process.

>A second point of attention is about the C-bindings. Those are incomplete and badly written, hence I cannot really say this API is fully stabilized while the C one may change at any moment. I already planned to rewrite those bindings.

I don't have an immediate need for C-bindings, but I believe that complete and stable C-bindings would be useful in many cases.

>That said, I think it's quite safe to assume it is currently usable in a Rust environment.

That's also my opinion. Thanks for confirming it.


I think the issue is resolved.
