### ISSUE TITLE
Question: Oath module?

### ISSUE THREAD

**Issue by pickfire** [breard-r/libreauth#18]
Is there a reason why `oath` is named `oath`? The description is just

> HOTP and TOTP authentication module

Or is it linked to the https://openauthentication.org/ organization? Is it a typo? Why isn't it otp?

**Comment by breard-r** [comment]
Yes, it is named `oath` because of the Initiative for Open Authentication (OATH). I should have provided a more precise description for this module since, in the future, it may not be limited to HOTP and TOTP: it may also include others standards referenced in the [OATH Reference Architecture](https://openauthentication.org/specifications-technical-resources/).

**Comment by pickfire** [comment]
Thanks, I believe it would be good if the module documentation mention about that so people could understand what oath and know what are the stuff that might be inside.
